Write-Host "Alte AI CRM secret preparation guidance only."
Write-Host ""
Write-Host "Safety rules:"
Write-Host "- Do not commit secrets."
Write-Host "- Do not paste secrets into chat, docs, GitHub, or screenshots."
Write-Host "- Store generated values only in a password manager and later in Secret Manager."
Write-Host "- This script does not call gcloud and does not write secret files."
Write-Host ""
Write-Host "JWT secret local generation example:"
Write-Host '[Convert]::ToBase64String((1..48 | ForEach-Object { Get-Random -Maximum 256 }))'
Write-Host ""
Write-Host "DB password:"
Write-Host "- Generate with a password manager or another secure local generator."
Write-Host "- Store it as alte-db-password later."
Write-Host ""
Write-Host "Anthropic API key:"
Write-Host "- Create or rotate in Anthropic Console."
Write-Host "- Never print it here."
Write-Host "- Store it as alte-anthropic-api-key later."
Write-Host ""
Write-Host "DATABASE_URL:"
Write-Host "- Build only after Cloud SQL connection details are known."
Write-Host "- Placeholder format: postgresql+asyncpg://alte_app:DB_PASSWORD@HOST:5432/alte_ai_crm"
Write-Host "- Store it as alte-database-url later."
Write-Host ""
Write-Host "Current phase remains preparation only. Do not create Secret Manager secrets until approved."
