// All UI strings — KA (Georgian) primary, EN secondary.
// Also: department schema, quick-reply seeds, sample answers.

const DEPTS = [
  { id:'admissions', icon:'graduation', color:'#074045',
    ka:'მიღება', en:'Admissions',
    kaShort:'მიღება', enShort:'Admissions',
    kaTopics:['ჩარიცხვის ვადები','აპლიკაცია','საბუთები'], enTopics:['Deadlines','Application','Documents'] },
  { id:'programs', icon:'building', color:'#0a5258',
    ka:'პროგრამები', en:'Programs',
    kaShort:'პროგრამები', enShort:'Programs',
    kaTopics:['ბაკალავრიატი','მაგისტრატურა','დოქტორანტურა'], enTopics:['Bachelor','Master','PhD'] },
  { id:'finance', icon:'money', color:'#16766f',
    ka:'დაფინანსება', en:'Tuition & Aid',
    kaShort:'დაფინანსება', enShort:'Tuition',
    kaTopics:['სწავლის ფასი','სტიპენდიები','განვადება'], enTopics:['Tuition','Scholarships','Plans'] },
  { id:'international', icon:'globe', color:'#1ca672',
    ka:'საერთ. სტუდენტები', en:'International',
    kaShort:'საერთ.', enShort:'Intl.',
    kaTopics:['ვიზა','საცხოვრებელი','ენა'], enTopics:['Visa','Housing','Language'] },
  { id:'medicine', icon:'heart', color:'#c2410c',
    ka:'მედიცინა · MD', en:'Medicine · MD',
    kaShort:'მედიცინა', enShort:'Medicine',
    kaTopics:['6-წლიანი MD','კლინიკები','აღიარება'], enTopics:['6-year MD','Clinicals','Recognition'] },
  { id:'library', icon:'book', color:'#5a6c6d',
    ka:'ბიბლიოთეკა', en:'Library',
    kaShort:'ბიბლიოთეკა', enShort:'Library', kaTopics:[], enTopics:[] },
  { id:'career', icon:'briefcase', color:'#5a6c6d',
    ka:'კარიერა', en:'Career',
    kaShort:'კარიერა', enShort:'Career', kaTopics:[], enTopics:[] },
  { id:'it', icon:'monitor', color:'#5a6c6d',
    ka:'IT დახმარება', en:'IT Help',
    kaShort:'IT', enShort:'IT', kaTopics:[], enTopics:[] },
];

const STRINGS = {
  KA: {
    appName:'Alte AI Assistant',
    appSub:'AI · 8 დეპარტამენტი',
    online:'ონლაინ · Claude Haiku',
    typing:'წერს…',
    trust:['პასუხები ',{strong:'alte.edu.ge'},'-ის ოფიციალური წყაროებიდან · არ ვიგონებთ ფაქტებს'],
    menu:'მენიუ',
    other:'სხვა',
    liveOperator:'ცოცხალი ოპერატორი',
    you:'ნინო',
    youRole:'აბიტურიენტი',
    greetingTitle:'გამარჯობა, ნინო 👋',
    greetingBody:'მე ვარ ალტეს AI ასისტენტი. სიდბარიდან აირჩიე დეპარტამენტი ან პირდაპირ მომწერე კითხვა — პასუხები ოფიციალური წყაროებიდან.',
    featTitle:'პოპულარული 2026',
    featDesc:'MD პროგრამა · ბაკალავრიატის ვადები · საერთ. სტუდენტი · დაფინანსება',
    quickReplies:[
      { emoji:'🎓', text:'როგორ ჩავაბარო ბაკალავრიატზე?' },
      { emoji:'💰', text:'რა ღირს სწავლა?' },
      { emoji:'🩺', text:'MD პროგრამა — გასაჩივრების ვადები?' },
      { emoji:'🌍', text:'საერთ. სტუდენტი ვარ, რა მჭირდება?' },
      { emoji:'📅', text:'როდის არის ჩარიცხვის ბოლო ვადა?' },
      { emoji:'📄', text:'რა საბუთები მჭირდება?' },
    ],
    composerPh:'მკითხე პროგრამაზე, მიღებაზე, დაფინანსებაზე…',
    composerHint:'Enter — გასაგზავნად · Shift+Enter — ახალი ხაზი',
    send:'გაგზავნა',
    attach:'მიამაგრე',
    voice:'ხმოვანი',
    new:'ახალი საუბარი',
    settings:'პარამეტრები',
    close:'დახურვა',
    expand:'სრულად',
    collapse:'შემცირება',
    sources:'წყაროები',
    showMore:'მეტი ',
    leaveContact:'დატოვე კონტაქტი',
    handoverTitle:'ოპერატორი ჩაერთო',
    handoverDept:'მიღების ოფისი',
    handoverHours:'სამუშაო საათები: ',
    handoverHoursVal:'ორშ–პარ 09:00–18:00',
    handoverWait:'ოპერატორი დაგიკავშირდება საშ. 3 სთ-ში. გსურს კონტაქტი დატოვო?',
    handoverYes:'დიახ, კონტაქტი',
    handoverNo:'დაელოდე',
    leadTitle:'დატოვე კონტაქტი',
    leadSub:'მიღების გუნდი დაგიკავშირდება 24 საათში.',
    leadName:'სახელი და გვარი',
    leadPhone:'ტელეფონი',
    leadEmail:'ელ.ფოსტა (არასავალდებულო)',
    leadInterest:'ინტერესის სფერო',
    leadConsent:'ვეთანხმები ',
    leadPrivacy:'კონფიდენციალურობის პოლიტიკას',
    leadSubmit:'გაგზავნა',
    settingsTitle:'პარამეტრები',
    settingsSub:'ენა, შეტყობინებები და კონფიდენციალურობა',
    settingsLang:'ენა · Language',
    settingsExp:'გამოცდილება',
    settingsPriv:'კონფიდენციალურობა',
    optSources:'წყაროების ბმულები',
    optSourcesSub:'alte.edu.ge ბმული ყოველ პასუხთან',
    optNotify:'დაბრუნების შეტყობინება',
    optNotifySub:'როცა ოპერატორი დაგიკავშირდება',
    optDark:'მუქი თემა',
    optDarkSub:'თვალისთვის უფრო კომფორტული',
    optClear:'საუბრის წაშლა',
    optClearSub:'ყველა შეტყობინება წაიშლება',
    deleteWord:'წაშლა',
    footVersion:'v2.0 · Claude AI',
    fileTitle:'ფაილის ანალიზი',
    fileDrop:'ჩააგდე PDF, DOCX ან სურათი',
    fileMax:'მაქს. 10MB · ვერ ვინახავთ ფაილს',
    filePick:'აირჩიე ფაილი',
    cancel:'გაუქმება',
    sendingCard:'მიღების გუნდი დაგიკავშირდება…',
    leadDone:'მიღების გუნდი დაგიკავშირდება 3 სთ-ში. მადლობა! 🌟',
    launcherTitle:'Alte AI Assistant',
    launcherSub:'დაგვისვი ნებისმიერი კითხვა',
    pageEyebrow:'მიღება 2026',
    pageTitle:'აღმოაჩინე შენი მომავალი ალტეში.',
    pageBody:'24 წლის გამოცდილება. 4 სკოლა — ბიზნესი, სამართალი, საერთ. მედიცინა, IT. სრულად ავტორიზებული.',
    statStudents:'სტუდენტი',
    statCountries:'ქვეყანა',
    statSchools:'სკოლა',
    navItems:['ჩვენ შესახებ','მიღება','სწავლა','სტუდენტებისთვის','აბიტურიენტებისთვის'],
    apply:'აპლიკაცია',
    quote:'„ალტეში მე ვისწავლე — როგორ ვისწავლო. ეს ცხოვრებისეული უნარია."',
    quoteBy:'— ლუკა, MD კურსდამთავრებული 2024',
    quoteBadge:'WHO · NCEQE აღიარებული',
    poweredBy:'Claude AI-ით ',
    poweredVerified:'ვერიფიცირებული წყაროები',
    emptyHint:'ან აირჩიე ქვემოთ მოცემული კითხვებიდან',
    chatActions:{ copy:'კოპირება', regen:'თავიდან', good:'კარგი', bad:'არ მომწონს' },
  },
  EN: {
    appName:'Alte AI Assistant',
    appSub:'AI · 8 departments',
    online:'Online · Claude Haiku',
    typing:'Typing…',
    trust:['Answers from ',{strong:'alte.edu.ge'},' official sources · no hallucinations'],
    menu:'Menu',
    other:'Other',
    liveOperator:'Live operator',
    you:'Nino',
    youRole:'Applicant',
    greetingTitle:'Hello, Nino 👋',
    greetingBody:"I'm Alte's AI assistant. Pick a department from the sidebar or just ask — answers come from official sources.",
    featTitle:'Trending 2026',
    featDesc:'MD program · Bachelor deadlines · International · Financial aid',
    quickReplies:[
      { emoji:'🎓', text:'How do I apply for a Bachelor?' },
      { emoji:'💰', text:'What does tuition cost?' },
      { emoji:'🩺', text:'MD program — deadlines?' },
      { emoji:'🌍', text:"I'm international — what do I need?" },
      { emoji:'📅', text:'When does enrollment close?' },
      { emoji:'📄', text:'What documents do I need?' },
    ],
    composerPh:'Ask about programs, admissions, tuition…',
    composerHint:'Enter to send · Shift+Enter for newline',
    send:'Send',
    attach:'Attach',
    voice:'Voice',
    new:'New chat',
    settings:'Settings',
    close:'Close',
    expand:'Expand',
    collapse:'Collapse',
    sources:'Sources',
    showMore:'More ',
    leaveContact:'Leave contact',
    handoverTitle:'Operator engaged',
    handoverDept:'Admissions Office',
    handoverHours:'Hours: ',
    handoverHoursVal:'Mon–Fri 09:00–18:00',
    handoverWait:'An operator will reach you in ~3h on average. Want to leave your contact?',
    handoverYes:'Yes, contact me',
    handoverNo:'Wait',
    leadTitle:'Leave your contact',
    leadSub:"Admissions team will reach out within 24 hours.",
    leadName:'Full name',
    leadPhone:'Phone',
    leadEmail:'Email (optional)',
    leadInterest:'Area of interest',
    leadConsent:'I agree to the ',
    leadPrivacy:'Privacy Policy',
    leadSubmit:'Send',
    settingsTitle:'Settings',
    settingsSub:'Language, notifications and privacy',
    settingsLang:'Language',
    settingsExp:'Experience',
    settingsPriv:'Privacy',
    optSources:'Source citations',
    optSourcesSub:'alte.edu.ge link with every answer',
    optNotify:'Callback notification',
    optNotifySub:'When an operator reaches out',
    optDark:'Dark theme',
    optDarkSub:'Easier on the eyes',
    optClear:'Clear conversation',
    optClearSub:'All messages will be deleted',
    deleteWord:'Delete',
    footVersion:'v2.0 · Claude AI',
    fileTitle:'File analysis',
    fileDrop:'Drop a PDF, DOCX or image',
    fileMax:'Max 10MB · we never store the file',
    filePick:'Choose file',
    cancel:'Cancel',
    sendingCard:'Admissions team will reach out…',
    leadDone:"Admissions team will be in touch within 3 hours. Thanks! 🌟",
    launcherTitle:'Alte AI Assistant',
    launcherSub:'Ask us anything',
    pageEyebrow:'Admissions 2026',
    pageTitle:'Discover your future at Alte.',
    pageBody:'24 years of experience. 4 schools — Business, Law, International Medicine, IT. Fully authorized.',
    statStudents:'students',
    statCountries:'countries',
    statSchools:'schools',
    navItems:['About','Admissions','Study','For Students','For Applicants'],
    apply:'Apply',
    quote:'"At Alte I learned — how to learn. That\'s a lifelong skill."',
    quoteBy:'— Luka, MD graduate 2024',
    quoteBadge:'WHO · NCEQE recognized',
    poweredBy:'Powered by Claude AI · ',
    poweredVerified:'verified sources',
    emptyHint:'Or pick a question below',
    chatActions:{ copy:'Copy', regen:'Regenerate', good:'Good', bad:"Doesn't help" },
  },
};

// Render a string-template (array of strings & {strong:'…'} objects) into JSX.
function T(spec){
  if (typeof spec === 'string') return spec;
  if (!Array.isArray(spec)) return null;
  return spec.map((p, i) => {
    if (typeof p === 'string') return <React.Fragment key={i}>{p}</React.Fragment>;
    if (p && p.strong) return <strong key={i}>{p.strong}</strong>;
    return null;
  });
}

// System prompt for Claude — keeps it on-brand and source-grounded.
function altePrompt(lang, dept){
  const deptHint = dept ? `User's current department context: ${dept.en} (${dept.ka}).` : '';
  if (lang === 'EN') {
    return `You are the official AI assistant for Alte University (alte.edu.ge), Tbilisi, Georgia. Founded in 2002. 4 schools: Business, Law, International Medicine (MD), IT. ~2,500 students from 45 countries. MD program is 6 years, English, ~$5,500/year, WHO & NCEQE recognized. ${deptHint}

Answer in English. Be CONCISE (3-5 short lines max, ~60 words). Format for a chat bubble — NO markdown headers (no #, no ##). Use **bold** sparingly for the single most important fact. Use bullet points (•) for short lists of 2-4 items. Never invent specific dates, prices, or eligibility rules — if unsure, say so and offer to connect to the live admissions team. End with a brief follow-up question when natural.`;
  }
  return `შენ ხარ ალტეს უნივერსიტეტის (alte.edu.ge) ოფიციალური AI ასისტენტი, თბილისი, საქართველო. დაარსდა 2002 წელს. 4 სკოლა: ბიზნესი, სამართალი, საერთაშორისო მედიცინა (MD), IT. ~2,500 სტუდენტი 45 ქვეყნიდან. MD პროგრამა — 6-წლიანი, ინგლისურენოვანი, ~$5,500/წელი, WHO და NCEQE აღიარებული. ${deptHint}

უპასუხე ქართულად. იყავი მოკლე — 3-5 ხაზი მაქს. (~60 სიტყვა). გააფორმე ჩათ-ბუშტისთვის — არ გამოიყენო markdown-სათაურები (არანაირი # ან ##). **გათამამება** გამოიყენე მხოლოდ ერთი ყველაზე მთავარი ფაქტისთვის. ბულეტები (•) — 2-4 ხაზის მოკლე ჩამონათვალისთვის. არასოდეს გამოიგონო ვადები, ფასები ან წესები — თუ არ იცი, თქვი და შესთავაზე ცოცხალ ოპერატორთან გადართვა. ბუნებრივ ადგილებში დაასრულე მოკლე დამატებითი კითხვით.`;
}

Object.assign(window, { DEPTS, STRINGS, T, altePrompt });
